### ISSUE TITLE
3dtile data is in 3dtile 1.1 standard and contains ktx2 features erro

### ISSUE THREAD

**Issue by yoyomule** [NASA-AMMOS/3DTilesRendererJS#852]
**Describe the bug**
I put the data in ion cesium into the demo system and it showed some errors. My 3dtile data is in 3dtile 1.1 standard and contains ktx2 features. Is this the reason for the error?

***Code***
TilesRenderer-3GzfWA9Z.js:1  TilesRenderer : Failed to load tile at url "0/0/3/2/2/0.glb".
m @ TilesRenderer-3GzfWA9Z.js:1
TilesRenderer-3GzfWA9Z.js:1  Error: THREE.GLTFLoader: setMeshoptDecoder must be called before loading compressed files
    at xt.loadBufferView (GLTFLoader-DkJa3Jo5.js:1:18219)
    at GLTFLoader-DkJa3Jo5.js:1:29460
    at kt._invokeOne (GLTFLoader-DkJa3Jo5.js:1:28887)
    at kt.getDependency (GLTFLoader-DkJa3Jo5.js:1:29410)
    at kt.loadAccessor (GLTFLoader-DkJa3Jo5.js:1:31153)
    at kt.getDependency (GLTFLoader-DkJa3Jo5.js:1:29364)
    at r (GLTFLoader-DkJa3Jo5.js:1:45909)
    at ce (GLTFLoader-DkJa3Jo5.js:1:46050)
    at kt.loadGeometries (GLTFLoader-DkJa3Jo5.js:1:38053)
    at kt.loadMesh (GLTFLoader-DkJa3Jo5.js:1:38368)
m @ TilesRenderer-3GzfWA9Z.js:1
TilesRenderer-3GzfWA9Z.js:1  TilesRenderer : Failed to load tile at url "0/1/1/0/5/0.glb".
m @ TilesRenderer-3GzfWA9Z.js:1
TilesRenderer-3GzfWA9Z.js:1  Error: THREE.GLTFLoader: setMeshoptDecoder must be called before loading compressed files
    at xt.loadBufferView (GLTFLoader-DkJa3Jo5.js:1:18219)
    at GLTFLoader-DkJa3Jo5.js:1:29460
    at kt._invokeOne (GLTFLoader-DkJa3Jo5.js:1:28887)
    at kt.getDependency (GLTFLoader-DkJa3Jo5.js:1:29410)
    at kt.loadAccessor (GLTFLoader-DkJa3Jo5.js:1:31153)
    at kt.getDependency (GLTFLoader-DkJa3Jo5.js:1:29364)
    at r (GLTFLoader-DkJa3Jo5.js:1:45909)
    at ce (GLTFLoader-DkJa3Jo5.js:1:46050)
    at kt.loadGeometries (GLTFLoader-DkJa3Jo5.js:1:38053)
    at kt.loadMesh (GLTFLoader-DkJa3Jo5.js:1:38368)

***Live example***

-https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/ionExample.html

**Screenshots**
![image](https://github.com/user-attachments/assets/1c38f85e-c455-4269-a8eb-985a4b7ca14d)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [ Edge,]

**Comment by gkjohnson** [comment]
Hello! GLTFLoader does not support KTX2 by default - a KTX2loader must be added to support the format. Similar to the DRACOLoader, as [outlined in the README](https://github.com/NASA-AMMOS/3DTilesRendererJS?tab=readme-ov-file#adding-draco-decompression-support).

Would you like to make PR for initializing the KTX2Loader in the ion example?

**Comment by phoenixbf** [comment]
You can try:
```
ktx2Loader = new THREE.KTX2Loader();
ktx2Loader.setTranscoderPath( /*PATH_BASIS_LIB*/ );
ktx2Loader.detectSupport( renderer );
```

Then in the tileset object:
`ts.manager.addHandler( /\.ktx2$/, ktx2Loader );`

**Comment by gkjohnson** [comment]
Yes sorry to clarify this can be done in two ways - by setting the KTX2 loader the same way the DRACO loader is in the example snippet:

```js
ktx2Loader = new THREE.KTX2Loader().setTranscoderPath( /*PATH_BASIS_LIB*/ );
gltfLoader.setKTX2Loader( ktx2Loader );
```

Or by using the GLTFLoader plugin for automatically setting up various gltf plugins for 3d tiles:

```js
// set up ktx2Loader...

tiles.registerPlugin( new GLTFExtensionsPlugin( {
  ktx2Loader: ktx2Loader,
} );
```
